---
apiVersion: v1
kind: Service
metadata:
  name: c10e-u8y-labs-gen-frontendproxy-$hostname-lb
  namespace: default
spec:
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  selector:
    opentelemetry.io/name: "c10e-u8y-labs-gen-frontendproxy"
  type: LoadBalancer
  loadBalancerIP: ""
  loadBalancerSourceRanges:
    - $myip
