{
 "title": "Lab Health",
 "tags": [
  "check",
  "lab"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "App - Requests rate by Frontend",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(app_frontend_requests[5m])) by (gateway)",
     "legendFormat": "{{gateway}}"
    }
   ]
  },
  {
   "title": "OTel collector - Memory Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace!=\"collectors\", container=\"opentelemetry-collector\"}) by (namespace)",
     "legendFormat": "usage-{{namespace}}"
    },
    {
     "expr": "sum(container_memory_cache{namespace!=\"collectors\", container=\"opentelemetry-collector\"}) by (namespace)",
     "legendFormat": "cache-{{namespace}}"
    }
   ]
  },
  {
   "title": "Prom Server - Memory Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"collectors\",container=\"prometheus-server\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"collectors\",container=\"prometheus-server\"})",
     "legendFormat": "cache"
    }
   ]
  },
  {
   "title": "Prom Server - Remote Storage Shards vs Sent Secs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(prometheus_remote_storage_sent_batch_duration_seconds_sum{job=\"prometheus\"}[5m]))",
     "legendFormat": "prometheus_remote_storage_sent_batch_duration_seconds_sum"
    },
    {
     "expr": "sum(prometheus_remote_storage_shards)",
     "legendFormat": "prometheus_remote_storage_shards"
    }
   ]
  },
  {
   "title": "Chronocollector - Memory Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"collectors\",container=\"chronocollector\"}) by (instance)",
     "legendFormat": "usage-{{instance}}"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"collectors\",container=\"chronocollector\"}) by (instance)",
     "legendFormat": "cache-{{instance}}"
    }
   ]
  },
  {
   "title": "Node Exporter - Memory Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"collectors\",container=\"node-exporter\"}) by (instance)",
     "legendFormat": "usage-{{instance}}"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"collectors\",container=\"node-exporter\"}) by (instance)",
     "legendFormat": "cache-{{instance}}"
    }
   ]
  },
  {
   "title": "Node - CPU by mode (secs)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_cpu_seconds_total) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Node - Context Switch Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_context_switches_total[5m])) by (node)",
     "legendFormat": "switches-{{node}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 } }
 ]
}