{
 "title": "Webstore Frontend",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Successful Requests in Last Hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(frontend_requests{frontend=\"frontend\", error=\"false\"}[1h])"
    }
   ]
  },
  {
   "title": "Failed Requests in Last Hour",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(frontend_requests{frontend=\"frontend\", error=\"true\"}[1h])"
    }
   ]
  },
  {
   "title": "Requests over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(frontend_requests{frontend=\"frontend\", error=\"false\"}[5m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(frontend_requests{frontend=\"frontend\", error=\"true\"}[5m])",
     "legendFormat": "Fails"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(frontend_requests_duration_sum[5m]))\n/\nsum(rate(frontend_requests_duration_count[5m]))"
    }
   ]
  },
  {
   "title": "Requests by API",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(app_frontend_requests{target!~\"/api/products/.*\"}) by (target)",
     "legendFormat": "{{target}}"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 17 } }
 ]
}